language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install:
    - pip install -r tests/requirements.txt
    - pip install -r requirements.txt
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install ordereddict; fi
script:
    - nosetests --with-coverage --cover-erase --cover-package=redscheduler
after_success:
    - coveralls
